apiVersion: v1
kind: Service
metadata:
  labels:
    app: ambipower
  name: devfile-ambipower
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: devfile-ambipower
  type: LoadBalancer